import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/navbar/Footer";
import NavbarScroll from "@/components/navbar/NavbarScroll";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative  flex flex-col  items-center  max-w-[1450px]  m-auto">
          <div className="fixed w-full max-w-[1400px]">
            <Navbar />
          </div>
        </div>
        <br />
        <div className="relative top-[85px] bg-white m-auto max-w-[1400px]">
          <div className="fixed m-auto max-w-[1400px] ">
            <NavbarScroll />
          </div>
        </div>
        <div className="relative  top-[180px] flex flex-col  items-center  max-w-[1450px]  m-auto">
          <hr className="h-[1px] fixed w-full top-[83px] bg-gray-200 z-[1]" />
          <div className="w-full ">{children}</div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
